import { createContext, useState, useContext } from "react";

const LanguageContext = createContext();

// Translations for all supported languages
export const translations = {
  en: {
    // Landing page
    searchPlaceholder: "Search posts...",
    heroTag: "A journal of slow living & visual stories",
    heroTitle: "The Daily Mosaic",
    heroSub: "Travel, food, photography, and the small moments that make up a life.",
    featuredStories: "Featured Stories",
    recentPosts: "Recent Posts",
    // Portal
    youAreSafeHere: "You are safe here",
    yourSafetyYourSilence: "Your safety, your silence.",
    portalDesc: "No account. No name. No trace. Submit evidence, talk to someone, or check your case — all hidden from any network monitor.",
    secureSession: "Secure Session",
    reportIncident: "Report an Incident",
    reportDesc: "Submit evidence safely. Photos, screenshots, your story. Encrypted and hidden before it leaves your device.",
    submitReport: "Submit report →",
    talkToCounselor: "Talk to a Counselor",
    chatDesc: "Real-time covert chat. Your messages travel as image frames — looks like browsing to any network monitor.",
    startChat: "Start chat →",
    checkMyCase: "Check My Case",
    statusDesc: "Have a token? Check the status of your previous submission and see if an NGO has responded.",
    checkStatus: "Check status →",
    emergencyTitle: "Emergency — I need help right now",
    emergencyDesc: "One tap. Submits your location and notifies the nearest NGO immediately. No typing needed.",
    // Evidence form
    whatHappened: "What happened?",
    descPlaceholder: "Describe the incident in your own words. Take your time...",
    useVoice: "Use voice instead",
    speakInYourLanguage: "Speak in your language — we'll convert it to text",
    yourCity: "Your City / District",
    whenDidThisHappen: "When did this happen?",
    safeWayToReach: "Safe way to reach you (optional)",
    contactHintPlaceholder: "e.g. 'Call only between 10am-12pm' or leave blank",
    uploadEvidence: "Upload Evidence (optional)",
    clickToUpload: "Click to upload screenshot or photo",
    fileSupport: "PNG, JPG, PDF supported · Compressed before upload",
    submitSecurely: "Submit Report Securely",
    pleaseDescribe: "Please describe what happened.",
    encryptingReport: "Encrypting and securing your report...",
    reportSubmitted: "Report Submitted Safely",
    reportSubmittedDesc: "Your report has been encrypted, hidden inside an image, and sent to our NGO partners.",
    saveYourToken: "Save your token below — it's your only way to check your case.",
    yourAnonymousToken: "Your Anonymous Token",
    tokenNote: "Write this down. Nobody can see it except you.",
    returnToPortal: "← Return to Safe Portal",
    backToPortal: "← Back to Portal",
    emergencyHelp: "Emergency Help",
    emergencyHelpDesc: "Pressing the button below will instantly share your location and notify the nearest NGO team. No typing needed.",
    sendEmergencyAlert: "Send Emergency Alert Now",
    fillDetailedReport: "I want to fill a detailed report instead",
    // User details
    yourName: "Your Name (optional)",
    namePlaceholder: "e.g. Priya (or leave blank)",
    yourAge: "Your Age (optional)",
    agePlaceholder: "e.g. 28",
    yourGender: "Gender (optional)",
    selectGender: "Select...",
    female: "Female",
    male: "Male",
    other: "Other",
    preferNotToSay: "Prefer not to say",
    relationshipToAbuser: "Relationship to abuser (optional)",
    relationshipPlaceholder: "e.g. Husband, Father, Employer",
    // NGO email
    sendToNgo: "Send to NGO",
    ngoEmailSent: "Evidence sent to NGO securely.",
    ngoEmailFailed: "Failed to send to NGO. Please try again.",
    // Download
    downloadEvidence: "Download Evidence Image",
    // Dead man's switch
    deadMansSwitch: "Dead Man's Switch",
    safetyFeature: "Safety Feature",
    deadManDesc: "If you don't check in within the selected time, the system automatically alerts the NGO team with your last known location — even if you can't reach your phone.",
    alertIfNoCheckin: "Alert if no check-in within:",
    hours12: "12 hours",
    hours24: "24 hours",
    hours48: "48 hours",
    activateSafetyTimer: "Activate Safety Timer",
    timeUntilAutoAlert: "TIME UNTIL AUTO-ALERT",
    imSafe: "I'm Safe — Reset Timer",
    checkedIn: "Checked In — Timer Reset!",
    tapImSafe: "Tap \"I'm Safe\" before the timer runs out.",
    ngoAlertedAuto: "If you don't, the NGO will be alerted automatically.",
  },
  hi: {
    searchPlaceholder: "पोस्ट खोजें...",
    heroTag: "धीमी जिंदगी और दृश्य कहानियों की पत्रिका",
    heroTitle: "द डेली मोज़ेक",
    heroSub: "यात्रा, भोजन, फोटोग्राफी, और जीवन के छोटे पल।",
    featuredStories: "विशेष कहानियाँ",
    recentPosts: "हालिया पोस्ट",
    youAreSafeHere: "आप यहाँ सुरक्षित हैं",
    yourSafetyYourSilence: "आपकी सुरक्षा, आपकी चुप्पी।",
    portalDesc: "कोई खाता नहीं। कोई नाम नहीं। कोई निशान नहीं। सबूत जमा करें, किसी से बात करें, या अपना केस देखें।",
    secureSession: "सुरक्षित सत्र",
    reportIncident: "घटना की रिपोर्ट करें",
    reportDesc: "सुरक्षित रूप से सबूत जमा करें। फ़ोटो, स्क्रीनशॉट, आपकी कहानी।",
    submitReport: "रिपोर्ट जमा करें →",
    talkToCounselor: "परामर्शदाता से बात करें",
    chatDesc: "रियल-टाइम गुप्त चैट। आपके संदेश इमेज फ्रेम के रूप में जाते हैं।",
    startChat: "चैट शुरू करें →",
    checkMyCase: "मेरा केस देखें",
    statusDesc: "टोकन है? अपनी पिछली सबमिशन की स्थिति देखें।",
    checkStatus: "स्थिति देखें →",
    emergencyTitle: "आपातकाल — मुझे अभी मदद चाहिए",
    emergencyDesc: "एक टैप। आपका स्थान भेजता है और निकटतम NGO को तुरंत सूचित करता है।",
    whatHappened: "क्या हुआ?",
    descPlaceholder: "अपने शब्दों में घटना का वर्णन करें...",
    useVoice: "आवाज़ का उपयोग करें",
    speakInYourLanguage: "अपनी भाषा में बोलें — हम टेक्स्ट में बदल देंगे",
    yourCity: "आपका शहर / जिला",
    whenDidThisHappen: "यह कब हुआ?",
    safeWayToReach: "आप तक पहुँचने का सुरक्षित तरीका (वैकल्पिक)",
    contactHintPlaceholder: "जैसे 'सुबह 10-12 बजे के बीच कॉल करें'",
    uploadEvidence: "सबूत अपलोड करें (वैकल्पिक)",
    clickToUpload: "स्क्रीनशॉट या फ़ोटो अपलोड करें",
    fileSupport: "PNG, JPG, PDF समर्थित",
    submitSecurely: "सुरक्षित रूप से रिपोर्ट जमा करें",
    pleaseDescribe: "कृपया बताएं कि क्या हुआ।",
    encryptingReport: "आपकी रिपोर्ट एन्क्रिप्ट हो रही है...",
    reportSubmitted: "रिपोर्ट सुरक्षित रूप से जमा हो गई",
    reportSubmittedDesc: "आपकी रिपोर्ट एन्क्रिप्ट की गई और NGO को भेज दी गई।",
    saveYourToken: "अपना टोकन नीचे सहेजें।",
    yourAnonymousToken: "आपका गुमनाम टोकन",
    tokenNote: "इसे लिख लें। यह सिर्फ आप देख सकते हैं।",
    returnToPortal: "← पोर्टल पर वापस",
    backToPortal: "← पोर्टल पर वापस",
    emergencyHelp: "आपातकालीन मदद",
    emergencyHelpDesc: "नीचे बटन दबाने से आपका स्थान साझा होगा और NGO को सूचित किया जाएगा।",
    sendEmergencyAlert: "अभी आपातकालीन अलर्ट भेजें",
    fillDetailedReport: "मैं विस्तृत रिपोर्ट भरना चाहती हूँ",
    yourName: "आपका नाम (वैकल्पिक)",
    namePlaceholder: "जैसे प्रिया",
    yourAge: "आपकी उम्र (वैकल्पिक)",
    agePlaceholder: "जैसे 28",
    yourGender: "लिंग (वैकल्पिक)",
    selectGender: "चुनें...",
    female: "महिला",
    male: "पुरुष",
    other: "अन्य",
    preferNotToSay: "बताना नहीं चाहती",
    relationshipToAbuser: "दुर्व्यवहार करने वाले से संबंध (वैकल्पिक)",
    relationshipPlaceholder: "जैसे पति, पिता, नियोक्ता",
    sendToNgo: "NGO को भेजें",
    ngoEmailSent: "सबूत NGO को सुरक्षित रूप से भेज दिया गया।",
    ngoEmailFailed: "NGO को भेजने में विफल। पुनः प्रयास करें।",
    downloadEvidence: "सबूत इमेज डाउनलोड करें",
    deadMansSwitch: "डेड मैन्स स्विच",
    safetyFeature: "सुरक्षा सुविधा",
    deadManDesc: "अगर आप चुने गए समय में चेक इन नहीं करती हैं, तो सिस्टम स्वचालित रूप से NGO को अलर्ट करेगा।",
    alertIfNoCheckin: "अगर चेक-इन नहीं तो अलर्ट:",
    hours12: "12 घंटे",
    hours24: "24 घंटे",
    hours48: "48 घंटे",
    activateSafetyTimer: "सुरक्षा टाइमर सक्रिय करें",
    timeUntilAutoAlert: "ऑटो-अलर्ट तक समय",
    imSafe: "मैं सुरक्षित हूँ — टाइमर रीसेट करें",
    checkedIn: "चेक इन हो गया — टाइमर रीसेट!",
    tapImSafe: "टाइमर खत्म होने से पहले \"मैं सुरक्षित हूँ\" दबाएं।",
    ngoAlertedAuto: "अगर नहीं दबाया, तो NGO को स्वचालित अलर्ट जाएगा।",
  },
  kn: {
    searchPlaceholder: "ಪೋಸ್ಟ್‌ಗಳನ್ನು ಹುಡುಕಿ...",
    heroTag: "ನಿಧಾನ ಜೀವನ ಮತ್ತು ದೃಶ್ಯ ಕಥೆಗಳ ಜರ್ನಲ್",
    heroTitle: "ದ ಡೈಲಿ ಮೊಸಾಯಿಕ್",
    heroSub: "ಪ್ರಯಾಣ, ಆಹಾರ, ಫೋಟೋಗ್ರಫಿ, ಮತ್ತು ಜೀವನದ ಸಣ್ಣ ಕ್ಷಣಗಳು.",
    featuredStories: "ವಿಶೇಷ ಕಥೆಗಳು",
    recentPosts: "ಇತ್ತೀಚಿನ ಪೋಸ್ಟ್‌ಗಳು",
    youAreSafeHere: "ನೀವು ಇಲ್ಲಿ ಸುರಕ್ಷಿತರಾಗಿದ್ದೀರಿ",
    yourSafetyYourSilence: "ನಿಮ್ಮ ಸುರಕ್ಷತೆ, ನಿಮ್ಮ ಮೌನ.",
    portalDesc: "ಖಾತೆ ಇಲ್ಲ. ಹೆಸರು ಇಲ್ಲ. ಯಾವುದೇ ಜಾಡು ಇಲ್ಲ.",
    secureSession: "ಸುರಕ್ಷಿತ ಸೆಶನ್",
    reportIncident: "ಘಟನೆಯನ್ನು ವರದಿ ಮಾಡಿ",
    reportDesc: "ಸುರಕ್ಷಿತವಾಗಿ ಪುರಾವೆ ಸಲ್ಲಿಸಿ.",
    submitReport: "ವರದಿ ಸಲ್ಲಿಸಿ →",
    talkToCounselor: "ಸಲಹೆಗಾರರೊಂದಿಗೆ ಮಾತನಾಡಿ",
    chatDesc: "ರಿಯಲ್-ಟೈಮ್ ಗುಪ್ತ ಚಾಟ್.",
    startChat: "ಚಾಟ್ ಪ್ರಾರಂಭಿಸಿ →",
    checkMyCase: "ನನ್ನ ಕೇಸ್ ನೋಡಿ",
    statusDesc: "ಟೋಕನ್ ಇದೆಯೇ? ನಿಮ್ಮ ಸ್ಥಿತಿ ನೋಡಿ.",
    checkStatus: "ಸ್ಥಿತಿ ನೋಡಿ →",
    emergencyTitle: "ತುರ್ತು — ನನಗೆ ಈಗ ಸಹಾಯ ಬೇಕು",
    emergencyDesc: "ಒಂದು ಟ್ಯಾಪ್. ನಿಮ್ಮ ಸ್ಥಳ ಕಳುಹಿಸುತ್ತದೆ.",
    whatHappened: "ಏನಾಯಿತು?",
    descPlaceholder: "ನಿಮ್ಮ ಮಾತುಗಳಲ್ಲಿ ಘಟನೆ ವಿವರಿಸಿ...",
    useVoice: "ಧ್ವನಿ ಬಳಸಿ",
    speakInYourLanguage: "ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಮಾತನಾಡಿ",
    yourCity: "ನಿಮ್ಮ ನಗರ / ಜಿಲ್ಲೆ",
    whenDidThisHappen: "ಇದು ಯಾವಾಗ ಆಯಿತು?",
    safeWayToReach: "ನಿಮ್ಮನ್ನು ತಲುಪಲು ಸುರಕ್ಷಿತ ಮಾರ್ಗ",
    contactHintPlaceholder: "ಉದಾ: ಬೆಳಿಗ್ಗೆ 10-12 ಮಧ್ಯೆ ಕರೆ ಮಾಡಿ",
    uploadEvidence: "ಪುರಾವೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    clickToUpload: "ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    fileSupport: "PNG, JPG, PDF ಬೆಂಬಲಿತ",
    submitSecurely: "ಸುರಕ್ಷಿತವಾಗಿ ವರದಿ ಸಲ್ಲಿಸಿ",
    pleaseDescribe: "ದಯವಿಟ್ಟು ಏನಾಯಿತು ಎಂದು ವಿವರಿಸಿ.",
    encryptingReport: "ನಿಮ್ಮ ವರದಿ ಎನ್‌ಕ್ರಿಪ್ಟ್ ಆಗುತ್ತಿದೆ...",
    reportSubmitted: "ವರದಿ ಸುರಕ್ಷಿತವಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ",
    reportSubmittedDesc: "ನಿಮ್ಮ ವರದಿ ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಿ NGO ಗೆ ಕಳುಹಿಸಲಾಗಿದೆ.",
    saveYourToken: "ನಿಮ್ಮ ಟೋಕನ್ ಕೆಳಗೆ ಉಳಿಸಿ.",
    yourAnonymousToken: "ನಿಮ್ಮ ಅನಾಮಧೇಯ ಟೋಕನ್",
    tokenNote: "ಇದನ್ನು ಬರೆಯಿರಿ. ನೀವು ಮಾತ್ರ ನೋಡಬಹುದು.",
    returnToPortal: "← ಪೋರ್ಟಲ್‌ಗೆ ಹಿಂತಿರುಗಿ",
    backToPortal: "← ಪೋರ್ಟಲ್‌ಗೆ ಹಿಂತಿರುಗಿ",
    emergencyHelp: "ತುರ್ತು ಸಹಾಯ",
    emergencyHelpDesc: "ಕೆಳಗಿನ ಬಟನ್ ಒತ್ತಿದರೆ ನಿಮ್ಮ ಸ್ಥಳ ಹಂಚಿಕೊಳ್ಳಲಾಗುತ್ತದೆ.",
    sendEmergencyAlert: "ಈಗ ತುರ್ತು ಎಚ್ಚರಿಕೆ ಕಳುಹಿಸಿ",
    fillDetailedReport: "ನಾನು ವಿವರವಾದ ವರದಿ ಬರೆಯಲು ಬಯಸುತ್ತೇನೆ",
    yourName: "ನಿಮ್ಮ ಹೆಸರು (ಐಚ್ಛಿಕ)",
    namePlaceholder: "ಉದಾ: ಪ್ರಿಯಾ",
    yourAge: "ನಿಮ್ಮ ವಯಸ್ಸು (ಐಚ್ಛಿಕ)",
    agePlaceholder: "ಉದಾ: 28",
    yourGender: "ಲಿಂಗ (ಐಚ್ಛಿಕ)",
    selectGender: "ಆಯ್ಕೆ ಮಾಡಿ...",
    female: "ಮಹಿಳೆ",
    male: "ಪುರುಷ",
    other: "ಇತರೆ",
    preferNotToSay: "ಹೇಳಲು ಬಯಸುವುದಿಲ್ಲ",
    relationshipToAbuser: "ದುರುಪಯೋಗಿಯೊಂದಿಗೆ ಸಂಬಂಧ (ಐಚ್ಛಿಕ)",
    relationshipPlaceholder: "ಉದಾ: ಪತಿ, ತಂದೆ, ಉದ್ಯೋಗದಾತ",
    sendToNgo: "NGO ಗೆ ಕಳುಹಿಸಿ",
    ngoEmailSent: "ಪುರಾವೆ NGO ಗೆ ಸುರಕ್ಷಿತವಾಗಿ ಕಳುಹಿಸಲಾಗಿದೆ.",
    ngoEmailFailed: "NGO ಗೆ ಕಳುಹಿಸಲು ವಿಫಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    downloadEvidence: "ಪುರಾವೆ ಚಿತ್ರ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
    deadMansSwitch: "ಡೆಡ್ ಮ್ಯಾನ್ಸ್ ಸ್ವಿಚ್",
    safetyFeature: "ಸುರಕ್ಷತಾ ವೈಶಿಷ್ಟ್ಯ",
    deadManDesc: "ಆಯ್ಕೆ ಮಾಡಿದ ಸಮಯದಲ್ಲಿ ಚೆಕ್ ಇನ್ ಮಾಡದಿದ್ದರೆ, ಸಿಸ್ಟಮ್ ಸ್ವಯಂಚಾಲಿತವಾಗಿ NGO ಗೆ ಎಚ್ಚರಿಕೆ ನೀಡುತ್ತದೆ.",
    alertIfNoCheckin: "ಚೆಕ್-ಇನ್ ಇಲ್ಲದಿದ್ದರೆ ಎಚ್ಚರಿಕೆ:",
    hours12: "12 ಗಂಟೆ",
    hours24: "24 ಗಂಟೆ",
    hours48: "48 ಗಂಟೆ",
    activateSafetyTimer: "ಸುರಕ್ಷತಾ ಟೈಮರ್ ಸಕ್ರಿಯಗೊಳಿಸಿ",
    timeUntilAutoAlert: "ಆಟೋ-ಎಚ್ಚರಿಕೆ ತನಕ ಸಮಯ",
    imSafe: "ನಾನು ಸುರಕ್ಷಿತ — ಟೈಮರ್ ರೀಸೆಟ್ ಮಾಡಿ",
    checkedIn: "ಚೆಕ್ ಇನ್ ಆಯಿತು — ಟೈಮರ್ ರೀಸೆಟ್!",
    tapImSafe: "ಟೈಮರ್ ಮುಗಿಯುವ ಮೊದಲು \"ನಾನು ಸುರಕ್ಷಿತ\" ಒತ್ತಿ.",
    ngoAlertedAuto: "ಒತ್ತದಿದ್ದರೆ, NGO ಗೆ ಸ್ವಯಂಚಾಲಿತ ಎಚ್ಚರಿಕೆ ಹೋಗುತ್ತದೆ.",
  },
  ta: {
    searchPlaceholder: "இடுகைகளைத் தேடு...",
    heroTag: "மெதுவான வாழ்க்கை மற்றும் காட்சி கதைகளின் பத்திரிகை",
    heroTitle: "தி டெய்லி மொசைக்",
    heroSub: "பயணம், உணவு, புகைப்படக்கலை, மற்றும் வாழ்க்கையின் சிறிய தருணங்கள்.",
    featuredStories: "சிறப்பு கதைகள்",
    recentPosts: "சமீபத்திய இடுகைகள்",
    youAreSafeHere: "நீங்கள் இங்கே பாதுகாப்பாக இருக்கிறீர்கள்",
    yourSafetyYourSilence: "உங்கள் பாதுகாப்பு, உங்கள் மௌனம்.",
    portalDesc: "கணக்கு இல்லை. பெயர் இல்லை. எந்த தடமும் இல்லை.",
    secureSession: "பாதுகாப்பான அமர்வு",
    reportIncident: "சம்பவத்தைப் புகாரளி",
    reportDesc: "பாதுகாப்பாக ஆதாரங்களை சமர்ப்பிக்கவும்.",
    submitReport: "அறிக்கை சமர்ப்பி →",
    talkToCounselor: "ஆலோசகருடன் பேசுங்கள்",
    chatDesc: "நிகழ்நேர இரகசிய அரட்டை.",
    startChat: "அரட்டை தொடங்கு →",
    checkMyCase: "என் வழக்கைப் பாருங்கள்",
    statusDesc: "டோக்கன் உள்ளதா? உங்கள் நிலையைப் பாருங்கள்.",
    checkStatus: "நிலையைப் பார் →",
    emergencyTitle: "அவசரம் — எனக்கு இப்போது உதவி வேண்டும்",
    emergencyDesc: "ஒரு தட்டு. உங்கள் இருப்பிடத்தை அனுப்புகிறது.",
    whatHappened: "என்ன நடந்தது?",
    descPlaceholder: "உங்கள் சொற்களில் சம்பவத்தை விவரிக்கவும்...",
    useVoice: "குரலைப் பயன்படுத்து",
    speakInYourLanguage: "உங்கள் மொழியில் பேசுங்கள்",
    yourCity: "உங்கள் நகரம் / மாவட்டம்",
    whenDidThisHappen: "இது எப்போது நடந்தது?",
    safeWayToReach: "உங்களை அடைய பாதுகாப்பான வழி",
    contactHintPlaceholder: "எ.கா: காலை 10-12 மணி இடையே அழைக்கவும்",
    uploadEvidence: "ஆதாரம் பதிவேற்று",
    clickToUpload: "ஸ்கிரீன்ஷாட் பதிவேற்று",
    fileSupport: "PNG, JPG, PDF ஆதரிக்கப்படுகிறது",
    submitSecurely: "பாதுகாப்பாக அறிக்கை சமர்ப்பி",
    pleaseDescribe: "என்ன நடந்தது என்று விவரிக்கவும்.",
    encryptingReport: "உங்கள் அறிக்கை குறியாக்கம் செய்யப்படுகிறது...",
    reportSubmitted: "அறிக்கை பாதுகாப்பாக சமர்ப்பிக்கப்பட்டது",
    reportSubmittedDesc: "உங்கள் அறிக்கை குறியாக்கம் செய்யப்பட்டு NGO க்கு அனுப்பப்பட்டது.",
    saveYourToken: "உங்கள் டோக்கனை கீழே சேமிக்கவும்.",
    yourAnonymousToken: "உங்கள் அநாமதேய டோக்கன்",
    tokenNote: "இதை எழுதுங்கள். நீங்கள் மட்டுமே பார்க்க முடியும்.",
    returnToPortal: "← போர்ட்டலுக்குத் திரும்பு",
    backToPortal: "← போர்ட்டலுக்குத் திரும்பு",
    emergencyHelp: "அவசர உதவி",
    emergencyHelpDesc: "கீழே உள்ள பொத்தானை அழுத்தினால் உங்கள் இருப்பிடம் பகிரப்படும்.",
    sendEmergencyAlert: "இப்போது அவசர எச்சரிக்கை அனுப்பு",
    fillDetailedReport: "விரிவான அறிக்கை எழுத விரும்புகிறேன்",
    yourName: "உங்கள் பெயர் (விருப்பமானது)",
    namePlaceholder: "எ.கா: பிரியா",
    yourAge: "உங்கள் வயது (விருப்பமானது)",
    agePlaceholder: "எ.கா: 28",
    yourGender: "பாலினம் (விருப்பமானது)",
    selectGender: "தேர்வு செய்...",
    female: "பெண்",
    male: "ஆண்",
    other: "மற்றவை",
    preferNotToSay: "சொல்ல விரும்பவில்லை",
    relationshipToAbuser: "தவறு செய்பவருடன் உறவு (விருப்பமானது)",
    relationshipPlaceholder: "எ.கா: கணவர், தந்தை, முதலாளி",
    sendToNgo: "NGO க்கு அனுப்பு",
    ngoEmailSent: "ஆதாரம் NGO க்கு பாதுகாப்பாக அனுப்பப்பட்டது.",
    ngoEmailFailed: "NGO க்கு அனுப்ப முடியவில்லை. மீண்டும் முயற்சிக்கவும்.",
    downloadEvidence: "ஆதார படத்தைப் பதிவிறக்கு",
    deadMansSwitch: "டெட் மேன்ஸ் ஸ்விட்ச்",
    safetyFeature: "பாதுகாப்பு அம்சம்",
    deadManDesc: "தேர்ந்தெடுக்கப்பட்ட நேரத்தில் செக் இன் செய்யவில்லை என்றால், கணினி தானாகவே NGO க்கு எச்சரிக்கை அனுப்பும்.",
    alertIfNoCheckin: "செக்-இன் இல்லாவிட்டால் எச்சரிக்கை:",
    hours12: "12 மணி நேரம்",
    hours24: "24 மணி நேரம்",
    hours48: "48 மணி நேரம்",
    activateSafetyTimer: "பாதுகாப்பு டைமரை இயக்கு",
    timeUntilAutoAlert: "ஆட்டோ-எச்சரிக்கை வரை நேரம்",
    imSafe: "நான் பாதுகாப்பாக — டைமர் ரீசெட்",
    checkedIn: "செக் இன் ஆனது — டைமர் ரீசெட்!",
    tapImSafe: "டைமர் முடிவதற்கு முன் \"நான் பாதுகாப்பாக\" அழுத்தவும்.",
    ngoAlertedAuto: "அழுத்தவில்லை என்றால், NGO க்கு தானாக எச்சரிக்கை போகும்.",
  },
  te: {
    searchPlaceholder: "పోస్ట్‌లు వెతకండి...",
    heroTag: "నెమ్మదిగా జీవించడం మరియు దృశ్య కథల జర్నల్",
    heroTitle: "ది డైలీ మొజాయిక్",
    heroSub: "ప్రయాణం, ఆహారం, ఫోటోగ్రఫీ, మరియు జీవితంలోని చిన్న క్షణాలు.",
    featuredStories: "ప్రత్యేక కథలు",
    recentPosts: "ఇటీవలి పోస్ట్‌లు",
    youAreSafeHere: "మీరు ఇక్కడ సురక్షితంగా ఉన్నారు",
    yourSafetyYourSilence: "మీ భద్రత, మీ మౌనం.",
    portalDesc: "ఖాతా లేదు. పేరు లేదు. ఏ ట్రేస్ లేదు.",
    secureSession: "సురక్షిత సెషన్",
    reportIncident: "సంఘటనను నివేదించండి",
    reportDesc: "సురక్షితంగా సాక్ష్యాలు సమర్పించండి.",
    submitReport: "నివేదిక సమర్పించు →",
    talkToCounselor: "కౌన్సెలర్‌తో మాట్లాడండి",
    chatDesc: "రియల్-టైమ్ రహస్య చాట్.",
    startChat: "చాట్ ప్రారంభించు →",
    checkMyCase: "నా కేసు చూడండి",
    statusDesc: "టోకెన్ ఉందా? మీ స్థితి చూడండి.",
    checkStatus: "స్థితి చూడు →",
    emergencyTitle: "అత్యవసరం — నాకు ఇప్పుడు సహాయం కావాలి",
    emergencyDesc: "ఒక ట్యాప్. మీ లొకేషన్ పంపుతుంది.",
    whatHappened: "ఏమి జరిగింది?",
    descPlaceholder: "మీ మాటల్లో సంఘటన వివరించండి...",
    useVoice: "వాయిస్ ఉపయోగించు",
    speakInYourLanguage: "మీ భాషలో మాట్లాడండి",
    yourCity: "మీ నగరం / జిల్లా",
    whenDidThisHappen: "ఇది ఎప్పుడు జరిగింది?",
    safeWayToReach: "మిమ్మల్ని సంప్రదించడానికి సురక్షిత మార్గం",
    contactHintPlaceholder: "ఉదా: ఉదయం 10-12 మధ్య కాల్ చేయండి",
    uploadEvidence: "సాక్ష్యం అప్‌లోడ్ చేయండి",
    clickToUpload: "స్క్రీన్‌షాట్ అప్‌లోడ్ చేయండి",
    fileSupport: "PNG, JPG, PDF మద్దతు ఉంది",
    submitSecurely: "సురక్షితంగా నివేదిక సమర్పించు",
    pleaseDescribe: "దయచేసి ఏమి జరిగిందో వివరించండి.",
    encryptingReport: "మీ నివేదిక ఎన్‌క్రిప్ట్ అవుతోంది...",
    reportSubmitted: "నివేదిక సురక్షితంగా సమర్పించబడింది",
    reportSubmittedDesc: "మీ నివేదిక ఎన్‌క్రిప్ట్ చేసి NGO కి పంపబడింది.",
    saveYourToken: "మీ టోకెన్ కింద సేవ్ చేయండి.",
    yourAnonymousToken: "మీ అనామక టోకెన్",
    tokenNote: "దీన్ని రాసుకోండి. మీరు మాత్రమే చూడగలరు.",
    returnToPortal: "← పోర్టల్‌కి తిరిగి వెళ్ళు",
    backToPortal: "← పోర్టల్‌కి తిరిగి వెళ్ళు",
    emergencyHelp: "అత్యవసర సహాయం",
    emergencyHelpDesc: "క్రింద బటన్ నొక్కితే మీ లొకేషన్ షేర్ అవుతుంది.",
    sendEmergencyAlert: "ఇప్పుడు అత్యవసర హెచ్చరిక పంపు",
    fillDetailedReport: "వివరమైన నివేదిక రాయాలనుకుంటున్నాను",
    yourName: "మీ పేరు (ఐచ్ఛికం)",
    namePlaceholder: "ఉదా: ప్రియ",
    yourAge: "మీ వయసు (ఐచ్ఛికం)",
    agePlaceholder: "ఉదా: 28",
    yourGender: "లింగం (ఐచ్ఛికం)",
    selectGender: "ఎంచుకోండి...",
    female: "స్త్రీ",
    male: "పురుషుడు",
    other: "ఇతర",
    preferNotToSay: "చెప్పడం ఇష్టం లేదు",
    relationshipToAbuser: "హింసించేవారితో సంబంధం (ఐచ్ఛికం)",
    relationshipPlaceholder: "ఉదా: భర్త, తండ్రి, యజమాని",
    sendToNgo: "NGO కి పంపు",
    ngoEmailSent: "సాక్ష్యం NGO కి సురక్షితంగా పంపబడింది.",
    ngoEmailFailed: "NGO కి పంపడం విఫలమైంది. మళ్ళీ ప్రయత్నించండి.",
    downloadEvidence: "సాక్ష్యం చిత్రం డౌన్‌లోడ్ చేయండి",
    deadMansSwitch: "డెడ్ మ్యాన్స్ స్విచ్",
    safetyFeature: "భద్రతా ఫీచర్",
    deadManDesc: "ఎంచుకున్న సమయంలో చెక్ ఇన్ చేయకపోతే, సిస్టమ్ స్వయంచాలకంగా NGO కి హెచ్చరిక పంపుతుంది.",
    alertIfNoCheckin: "చెక్-ఇన్ లేకపోతే హెచ్చరిక:",
    hours12: "12 గంటలు",
    hours24: "24 గంటలు",
    hours48: "48 గంటలు",
    activateSafetyTimer: "భద్రతా టైమర్ యాక్టివేట్ చేయండి",
    timeUntilAutoAlert: "ఆటో-హెచ్చరిక వరకు సమయం",
    imSafe: "నేను సురక్షితం — టైమర్ రీసెట్",
    checkedIn: "చెక్ ఇన్ అయింది — టైమర్ రీసెట్!",
    tapImSafe: "టైమర్ అయిపోయే ముందు \"నేను సురక్షితం\" నొక్కండి.",
    ngoAlertedAuto: "నొక్కకపోతే, NGO కి ఆటోమేటిక్ హెచ్చరిక వెళ్తుంది.",
  },
  bn: {
    searchPlaceholder: "পোস্ট খুঁজুন...",
    heroTag: "ধীর জীবন এবং দৃশ্য গল্পের জার্নাল",
    heroTitle: "দ্য ডেইলি মোজাইক",
    heroSub: "ভ্রমণ, খাবার, ফটোগ্রাফি এবং জীবনের ছোট মুহূর্ত।",
    featuredStories: "বিশেষ গল্প",
    recentPosts: "সাম্প্রতিক পোস্ট",
    youAreSafeHere: "আপনি এখানে নিরাপদ",
    yourSafetyYourSilence: "আপনার নিরাপত্তা, আপনার নীরবতা।",
    portalDesc: "কোনো অ্যাকাউন্ট নেই। কোনো নাম নেই। কোনো ট্রেস নেই।",
    secureSession: "নিরাপদ সেশন",
    reportIncident: "ঘটনা রিপোর্ট করুন",
    reportDesc: "নিরাপদে প্রমাণ জমা দিন।",
    submitReport: "রিপোর্ট জমা দিন →",
    talkToCounselor: "কাউন্সেলরের সাথে কথা বলুন",
    chatDesc: "রিয়েল-টাইম গোপন চ্যাট।",
    startChat: "চ্যাট শুরু করুন →",
    checkMyCase: "আমার কেস দেখুন",
    statusDesc: "টোকেন আছে? আপনার স্থিতি দেখুন।",
    checkStatus: "স্থিতি দেখুন →",
    emergencyTitle: "জরুরি — আমার এখনই সাহায্য দরকার",
    emergencyDesc: "এক ট্যাপ। আপনার অবস্থান পাঠায়।",
    whatHappened: "কী হয়েছে?",
    descPlaceholder: "আপনার কথায় ঘটনা বর্ণনা করুন...",
    useVoice: "ভয়েস ব্যবহার করুন",
    speakInYourLanguage: "আপনার ভাষায় বলুন",
    yourCity: "আপনার শহর / জেলা",
    whenDidThisHappen: "এটা কবে হয়েছিল?",
    safeWayToReach: "আপনার কাছে পৌঁছানোর নিরাপদ উপায়",
    contactHintPlaceholder: "যেমন: সকাল ১০-১২টার মধ্যে কল করুন",
    uploadEvidence: "প্রমাণ আপলোড করুন",
    clickToUpload: "স্ক্রিনশট আপলোড করুন",
    fileSupport: "PNG, JPG, PDF সমর্থিত",
    submitSecurely: "নিরাপদে রিপোর্ট জমা দিন",
    pleaseDescribe: "অনুগ্রহ করে কী হয়েছে বলুন।",
    encryptingReport: "আপনার রিপোর্ট এনক্রিপ্ট হচ্ছে...",
    reportSubmitted: "রিপোর্ট নিরাপদে জমা হয়েছে",
    reportSubmittedDesc: "আপনার রিপোর্ট এনক্রিপ্ট করে NGO-তে পাঠানো হয়েছে।",
    saveYourToken: "নিচে আপনার টোকেন সেভ করুন।",
    yourAnonymousToken: "আপনার বেনামী টোকেন",
    tokenNote: "এটি লিখে রাখুন। শুধু আপনি দেখতে পারবেন।",
    returnToPortal: "← পোর্টালে ফিরুন",
    backToPortal: "← পোর্টালে ফিরুন",
    emergencyHelp: "জরুরি সাহায্য",
    emergencyHelpDesc: "নিচের বোতামে চাপলে আপনার অবস্থান শেয়ার হবে।",
    sendEmergencyAlert: "এখনই জরুরি সতর্কতা পাঠান",
    fillDetailedReport: "আমি বিস্তারিত রিপোর্ট লিখতে চাই",
    yourName: "আপনার নাম (ঐচ্ছিক)",
    namePlaceholder: "যেমন: প্রিয়া",
    yourAge: "আপনার বয়স (ঐচ্ছিক)",
    agePlaceholder: "যেমন: ২৮",
    yourGender: "লিঙ্গ (ঐচ্ছিক)",
    selectGender: "নির্বাচন করুন...",
    female: "মহিলা",
    male: "পুরুষ",
    other: "অন্যান্য",
    preferNotToSay: "বলতে চাই না",
    relationshipToAbuser: "নির্যাতনকারীর সাথে সম্পর্ক (ঐচ্ছিক)",
    relationshipPlaceholder: "যেমন: স্বামী, বাবা, মালিক",
    sendToNgo: "NGO-তে পাঠান",
    ngoEmailSent: "প্রমাণ নিরাপদে NGO-তে পাঠানো হয়েছে।",
    ngoEmailFailed: "NGO-তে পাঠাতে ব্যর্থ। আবার চেষ্টা করুন।",
    downloadEvidence: "প্রমাণ ছবি ডাউনলোড করুন",
    deadMansSwitch: "ডেড ম্যানস সুইচ",
    safetyFeature: "নিরাপত্তা ফিচার",
    deadManDesc: "নির্বাচিত সময়ে চেক ইন না করলে, সিস্টেম স্বয়ংক্রিয়ভাবে NGO-কে সতর্ক করবে।",
    alertIfNoCheckin: "চেক-ইন না হলে সতর্কতা:",
    hours12: "১২ ঘণ্টা",
    hours24: "২৪ ঘণ্টা",
    hours48: "৪৮ ঘণ্টা",
    activateSafetyTimer: "নিরাপত্তা টাইমার সক্রিয় করুন",
    timeUntilAutoAlert: "অটো-সতর্কতা পর্যন্ত সময়",
    imSafe: "আমি নিরাপদ — টাইমার রিসেট",
    checkedIn: "চেক ইন হয়েছে — টাইমার রিসেট!",
    tapImSafe: "টাইমার শেষ হওয়ার আগে \"আমি নিরাপদ\" চাপুন।",
    ngoAlertedAuto: "না চাপলে, NGO-কে স্বয়ংক্রিয় সতর্কতা যাবে।",
  },
};

// Language metadata for the switcher
export const languages = [
  { code: "en", label: "English", native: "English" },
  { code: "hi", label: "Hindi", native: "हिन्दी" },
  { code: "kn", label: "Kannada", native: "ಕನ್ನಡ" },
  { code: "ta", label: "Tamil", native: "தமிழ்" },
  { code: "te", label: "Telugu", native: "తెలుగు" },
  { code: "bn", label: "Bengali", native: "বাংলা" },
];

// Speech recognition language codes
export const speechLangCodes = {
  en: "en-IN",
  hi: "hi-IN",
  kn: "kn-IN",
  ta: "ta-IN",
  te: "te-IN",
  bn: "bn-IN",
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem("sv-lang") || "en");

  const changeLang = (code) => {
    setLang(code);
    localStorage.setItem("sv-lang", code);
  };

  const t = (key) => translations[lang]?.[key] || translations.en[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, changeLang, t, languages, speechLangCodes }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
